### ISSUE TITLE
regex takes too much memory for srt

### ISSUE THREAD

**Issue by david-soyez** [captioning/captioning#36]
The regex takes too much memory for subtitles (subrip) with mutiples lines of captions and crash php:
`segmentation fault (core dumped)`

I think the parser should not use a regular expression for subrip.

**Comment by delphiki** [comment]
Never encountered anything like this. 
Could you provide us with the file you used?

**Comment by david-soyez** [comment]
https://gist.github.com/david-soyez/2b2e5629d8f65b305d6ff8dd4f9797a5

**Comment by david-soyez** [comment]
I have uploaded on my server and it is even worse, subtitles that worked locally on my computer do not on the server. The server has 1 or 2GB of memory.

**Comment by delphiki** [comment]
I've tested your file and had no trouble parsing it (after fixing the index of the last cue which was throwing an exception).

I've tested it with very low memory_limit, and it failed below 5M (which could be expected).
So I doubt the problem comes from the lib itself (even if I'm not closed to the discussion).

What versions of PHP and the lib are you using?

**Comment by delphiki** [comment]
This is now fixed using non-strict mode for subrip parsing.
